apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ec-cli-main-ci
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ec-cli-main-ci
    app.kubernetes.io/part-of: ec-main-ci
  name: ec-cli-main-ci
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: ec-cli-main-ci
status:
  loadBalancer: {}
